### ISSUE TITLE
i cannot run it locally

### ISSUE THREAD

**Issue by channingbreeze** [TheMightyFingers/mightyeditor#61]
When i execute node Server.js , i got errors like this
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/lixin/Phaser/mightyeditor-master/server/node_modules/nodemailer/lib/nodemailer.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
can anybody help me?

**Comment by hotator** [comment]
There is a possible issue with newer versions of nodemailer.

You can force the server to use a specific version if you edit the package.json.

Change the >= in line 18 to = and rebuild the node modules.

This should work.
